# flutter pub get
# flutter pub run flutter_launcher_icons:main

name: mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  flutter_html: ^3.0.0-beta.2
  http: ^1.1.0
  provider: ^6.0.5
  flutter_native_splash: ^2.3.4
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/calvary.jpg"
